/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/BlackPawn.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_68.geometry}
        material={materials.BlackPieces}
        position={[0.088, 0.04, -0.123]}
        rotation={[-Math.PI, 0.58, -Math.PI]}
      />
    </group>
  )
}

useGLTF.preload('/BlackPawn.gltf')