/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/BlackQueen.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.BlackPieces}
        position={[0.123, 0.04, -0.018]}
        rotation={[-Math.PI, 0.321, -Math.PI]}
        scale={[0.015, 0.016, 0.015]}
      />
    </group>
  )
}

useGLTF.preload('/BlackQueen.gltf')
