/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/BlackBishop.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.BlackPieces}
        position={[0.124, 0.04, -0.054]}
        rotation={[0, 0.928, 0]}
        scale={[0.015, 0.016, 0.015]}
      />
    </group>
  )
}

useGLTF.preload('/BlackBishop.gltf')